use_frameworks!

platform :ios, '8.0'

target 'CNLiveCategoryModule_Example' do
  pod 'CNLiveCategoryModule', :path => '../'

  target 'CNLiveCategoryModule_Tests' do
    inherit! :search_paths

    
  end
end
